import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
	title: 'RealChat',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className='dark'>
			<body className='antialiased font-poppins scroll-smooth'>
				{children}
				<Toaster position='top-center' />
			</body>
		</html>
	);
}
